services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: zpi-tailscale-prod
    hostname: ${BACKEND_HOSTNAME}
    restart: always
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY_PROD}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-tags=tag:prod,tag:backend
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - zpi-backend-node-net
    healthcheck:
      test: [ "CMD", "sh", "/usr/local/bin/ts-healthcheck.sh" ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 15s


  backend:
    build: .
    image: zpi-kkm-backend:${APP_VERSION}
    container_name: zpi-backend-prod
    restart: always
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - API_BASE_URL=${API_BASE_URL}
      - TAILSCALE__TAILNET_ID=${TAILSCALE__TAILNET_ID}
      - TAILSCALE__TAILSCALE_API_CLIENT_ID=${TAILSCALE__TAILSCALE_API_CLIENT_ID}
      - TAILSCALE__TAILSCALE_API_CLIENT_SECRET=${TAILSCALE__TAILSCALE_API_CLIENT_SECRET}
      - SERVER_ID=${SERVER_ID}
      - CASSANDRA__LOCAL_DATACENTER=${CASSANDRA__LOCAL_DATACENTER}
      - CASSANDRA__USERNAME=${CASSANDRA__USERNAME}
      - CASSANDRA__PASSWORD=${CASSANDRA__PASSWORD}
      - CASSANDRA__KEYSPACE=${CASSANDRA__KEYSPACE}
    network_mode: service:tailscale
    depends_on:
      tailscale:
        condition: service_healthy

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: zpi-tunnel-prod
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - zpi-backend-node-net
    depends_on:
      tailscale:
        condition: service_healthy
      backend:
        condition: service_started

networks:
  zpi-backend-node-net:
    driver: bridge

volumes:
  tailscale-data:
