services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: zpi-tailscale-test
    hostname: ${BACKEND_HOSTNAME}
    restart: always
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY_TEST}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-tags=tag:test,tag:backend
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - zpi-backend-node-net

  backend:
    build: .
    image: zpi-kkm-backend:${APP_VERSION}
    container_name: zpi-backend-test
    restart: always
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - API_BASE_URL=${API_BASE_URL}
      - TAILNET_ID=${TAILNET_ID}
      - TAILSCALE_API_CLIENT_ID=${TAILSCALE_API_CLIENT_ID}
      - TAILSCALE_API_CLIENT_SECRET=${TAILSCALE_API_CLIENT_SECRET}
      - SERVER_ID=${SERVER_ID}
    network_mode: service:tailscale
    depends_on:
      - tailscale

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: zpi-tunnel-test
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - zpi-backend-node-net
    depends_on:
      - backend

networks:
  zpi-backend-node-net:
    driver: bridge

volumes:
  tailscale-data:
