services:
  backend:
    build: .
    image: zpi-kkm-backend:${APP_VERSION}
    container_name: zpi-backend-dev
    restart: always
    env_file: ./src/.env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - API_BASE_URL=${API_BASE_URL}
      - TAILNET_ID=${TAILNET_ID}
      - TAILSCALE_API_CLIENT_ID=${TAILSCALE_API_CLIENT_ID}
      - TAILSCALE_API_CLIENT_SECRET=${TAILSCALE_API_CLIENT_SECRET}
      - SERVER_ID=${SERVER_ID}
    expose:
      - "8000"
    ports:
      - "8000:8000"